% -------------------------------------------------------------------
%  Generated by MATLAB on 25-Jan-2019 00:57:46
%  MATLAB version: 8.4.0.150421 (R2014b)
% -------------------------------------------------------------------
saveVarsMat = load('bai1.mat');


hinhAnh = saveVarsMat.hinhAnh; % <625x500x3 uint8> too many elements


clear saveVarsMat;
